### ISSUE TITLE
AttributeError: 'module' object has no attribute 'SSLContext'                                                          

### ISSUE THREAD

**Issue by guzhaoyuan** [guzhaoyuan/smartLock#1]
python -m flask run

Traceback (most recent call last):
  File "/usr/lib/python2.7/runpy.py", line 162, in _run_module_as_main
    "__main__", fname, loader, pkg_name)
  File "/usr/lib/python2.7/runpy.py", line 72, in _run_code
    exec code in run_globals
  File "/usr/local/lib/python2.7/dist-packages/flask/__main__.py", line 14, in <module>
    main(as_module=True)
  File "/usr/local/lib/python2.7/dist-packages/flask/cli.py", line 894, in main
    cli.main(args=args, prog_name=name)
  File "/usr/local/lib/python2.7/dist-packages/flask/cli.py", line 557, in main
    return super(FlaskGroup, self).main(*args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/click/core.py", line 697, in main
    rv = self.invoke(ctx)
  File "/usr/local/lib/python2.7/dist-packages/click/core.py", line 1064, in invoke
    sub_ctx = cmd.make_context(cmd_name, args, parent=ctx)
  File "/usr/local/lib/python2.7/dist-packages/click/core.py", line 621, in make_context
    self.parse_args(ctx, args)
  File "/usr/local/lib/python2.7/dist-packages/click/core.py", line 880, in parse_args
    value, args = param.handle_parse_result(ctx, opts, args)
  File "/usr/local/lib/python2.7/dist-packages/click/core.py", line 1404, in handle_parse_result
    self.callback, ctx, self, value)
  File "/usr/local/lib/python2.7/dist-packages/click/core.py", line 78, in invoke_param_callback
    return callback(ctx, param, value)
  File "/usr/local/lib/python2.7/dist-packages/flask/cli.py", line 693, in _validate_key
    is_context = isinstance(cert, ssl.SSLContext)
AttributeError: 'module' object has no attribute 'SSLContext'

**Comment by guzhaoyuan** [comment]
似乎是python 2.7.6的锅，SSLContext是python2.7.9引入的
https://stackoverflow.com/questions/28228214/ssl-module-object-has-no-attribute-sslcontext

**Comment by guzhaoyuan** [comment]
https://serverfault.com/a/725064
This answer solved problem. upgrade to python 2.7.9+.
It seem the code is not compatible with python3 either.
